config/routes.rb
Rails.application.routes.draw do
  
  
  resources :gallery_images
  resources :orders
  root 'home#index'
  
  get 'home/Q_and_A', to: 'home#Q_and_A'
  get 'home/login', to: 'home#login'
  get 'home/childish', to: 'home#childish'
  get 'home/printable', to: 'home#printable'
  get 'home/accessories', to: 'home#accessories'
  get 'home/articles', to: 'home#articles'
  get 'home/adult', to: 'home#adult'
  get 'home/boxes', to: 'home#boxes'
  get 'home/gifts', to: 'home#gifts'
  get 'home/memories', to: 'home#memories'
  get 'home/others', to: 'home#others'
  get 'home/wedding', to: 'home#wedding'

  resources :galleries do
    resources :images, :only => [:create, :destroy] # support #create and #destroy
  end 
  resources :models
  resources :categories
  resources :events
  resources :social_networks
  resources :profiles
  resources :contacts
  resources :questions

  namespace :admin do
    get 'home/index'
  end

  devise_for :users, :controllers => { :passwords => 'scope/passwords', :registrations => 'scope/registrations'}
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_category.html.erb
<div class="card-category">
  <div class="card-body">
    <div class="container">
      <div class="row">
        <div class="col-xs" style="padding: 0;">
          
          <p class="card-category-title">
            Categorías
          </p>
          <hr class="card-category-divider">
          <ul class="card-category-list">
            <%if @categories.empty?  %>
              <li> </li>
            <% else %>
              <% @categories.each do |categories| %>
                  <li><%= categories.name %></li>
              <% end %>
            <% end %>
          </ul>  
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer-admin.html.erb
<footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                       <!--  <li>
                            <a href="http://www.creative-tim.com">
                                Creative Tim
                            </a>
                        </li>
                        <li>
                            <a href="http://blog.creative-tim.com">
                               Blog
                            </a>
                        </li>
                        <li>
                            <a href="http://www.creative-tim.com/license">
                                Licenses
                            </a>
                        </li> -->
                    </ul>
                </nav>
                <div class="copyright pull-right">
                    Hecho con <i class="fa fa-heart heart"></i> por Gaby González
                </div>
            </div>
        </footer>

app/views/shared/_footer.html.erb
<!-- Footer -->
    <footer class="py-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <p class="part1footer"> 
              Rangel Paper 
              <br>
            
              <i class="fa fa-map-marker fa-fw" aria-hidden="true"></i>
              Address: Isla de Margarita - Venezuela
              <br>
   
              <i class="fa fa-phone fa-fw" aria-hidden="true"></i>
              Phone: +58 426.787.60.99
              <br>
       
              <i class="fa fa-envelope fa-fw" aria-hidden="true"></i>
              Email: rangelpaper@gmail.com
            </p>
          </div>
          <div class="col-md-4">
            <p class="part1footer"> 
              Información
              <br>
             
              <%= link_to new_contact_path, class: "text-white" do %>
                <i class="fa fa-phone fa-fw" aria-hidden="true"></i> Contacto
              <% end %>
              <br>
              
              <%= link_to home_Q_and_A_url, class: "text-white" do %>
                <i class="fa fa-info fa-fw" aria-hidden="true"></i> Preguntas Frecuentes
              <% end %>
              <br>
             
              <i class="fa fa-download fa-fw" aria-hidden="true"></i> 
              Imprimibles
            </p>
          </div>
          <div class="col-md-3">
          </div>
        </div>
      </div>
      <!-- /.container -->
    </footer>
    <footer class="py-footerpink">
      <div class="container">
        <p class="m-0 text-center text-white">Rangel Paper. Todos los derechos reservados</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/shared/_header-admin.html.erb
<div class="main-panel">

    <nav class="navbar-admin navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<p> <i class="ti-user"></i> <%= current_user.email %></p>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
    </nav>

app/views/shared/_header.html.erb
  <div class="row">
    <div class="col-md-6 text-center" style="margin-bottom: 20px">
      <%= image_tag("LOGO.jpg", size: "331x125") %>
    </div>
    <div class="col-md-6">
    </div>
  </div>

<!-- Navigation -->
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav m-auto">
            <li class="nav-item active">
              <a class="nav-link " href="#">INICIO
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                INVITACIONES
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">INFANTILES</a>
                <a class="dropdown-item" href="#">ADULTOS</a>
                <a class="dropdown-item" href="#">BODA</a>
                <a class="dropdown-item" href="#">OTROS EVENTOS</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                DETALLES Y COMPLEMENTOS
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">RECUERDITOS</a>
                <a class="dropdown-item" href="#">REGALOS DE SALIDA</a>
                <a class="dropdown-item" href="#">CAJITAS/BOLSITAS</a>
                <a class="dropdown-item" href="#">COMPLEMENTOS</a>
                <a class="dropdown-item" href="#">ARTICULOS DE MADERA</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">IMPRIMIBLES</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">CONTACTO</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/shared/_headerlogin.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-sm text-center" style="margin-bottom: 20px">
      <%= image_tag("LOGO.jpg", class: "logo-header") %>
    </div>

    <div class="col-sm text-center">
        <p>
          <h3 style="color: #fe51bb;margin-top: 50px;">!Hola!</h3>
          <% if current_user %>
            
            <% if current_user.email == 'ggm.gaby06@gmail.com' %>
              <%= link_to admin_home_index_url do %>
                <h6 style="color: rgb(161, 161, 162)"> Acceder a Admin </h6>
              <% end %>
            <% end %>

            <%= link_to destroy_user_session_path, :method => :delete do %>
              <h6 style="color: rgb(161, 161, 162)"> <%= current_user.email %> | Cerrar Sesión </h6>
            <% end %>

          <% else %>
            <%= link_to home_login_url do %>
              <h6 style="color: rgb(161, 161, 162)">Crear Cuenta | Accesar</h6>
            <% end %>
          <% end %>
        </p>
    </div>

    <div class="col-sm">
      <div class="card-header-car">
            <div class="card-body" style="padding: 0;">
              <div class="container">
                <div class="row">
                  <div class="col-xs" style="padding: 0;">
                      <%= image_tag("icon-car.png", class: "card-header-icon") %>
                  </div>
                  <div class="mycontent-left"></div>
                  <div class="col-xs" style="padding: 0;">
                    <p class="card-header-pink">
                      Mi carrito:
                    </p>
                    <p class="card-header-grey">
                      (vacío)
                    </p> 
                  </div>
                </div>
              </div>
            </div>
          </div>
    </div>
  </div>

</div>

app/views/shared/_menu-admin.html.erb
<div class="sidebar" data-background-color="white" data-active-color="danger">
    <!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->
    <div class="sidebar-wrapper">
            <div class="logo">
                <%= image_tag("LOGO.jpg", class: "logo-header") %>
            </div>

            <ul class="nav">
                <li class="active">
                    <%= link_to admin_home_index_url do %>
                        <i class="ti-home"></i>
                        <p>Inicio</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to new_profile_url do %>
                        <i class="ti-user"></i>
                        <p>Perfil</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to orders_url do %>
                        <i class="fa fa-book"></i>
                        <p>Pedidos</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to contacts_path do %>
                        <i class="ti-comment-alt"></i>
                        <p>Contactos</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to events_path do %>
                        <i class="fa fa-gift"></i>
                        <p>Eventos</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to categories_path do %>
                        <i class="ti-menu-alt"></i>
                        <p>Categorías</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to models_path do %>
                        <i class="fa fa-bookmark"></i>
                        <p>Modelo</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to galleries_path do %>
                        <i class="ti-gallery"></i>
                        <p>Galeria</p>
                    <% end %>
                </li>
                <li>
                    <%= link_to questions_path do %>
                        <i class="fa fa-question-circle"></i>
                        <p>Preguntas Frecuentes</p>
                    <% end %>
                </li>
				<li >
                    <%= link_to destroy_user_session_path, :method => :delete do %>
                        <i class="fa fa-sign-out"></i>
                        <p>Cerrar Sesión</p>
                    <% end %>
                </li>
            </ul>
    </div>
</div>

app/views/shared/_menu.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav m-auto">
            <li class="nav-item active">
              <%= link_to "INICIO", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                INVITACIONES
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "INFANTILES", home_childish_url, class: "dropdown-item" %>
                <%= link_to "ADULTOS", home_adult_url, class: "dropdown-item" %>
                <%= link_to "BODA", home_wedding_url, class: "dropdown-item" %>
                <%= link_to "OTROS EVENTOS", home_others_url, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                DETALLES Y COMPLEMENTOS
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "RECUERDITOS", home_memories_url, class: "dropdown-item" %>
                <%= link_to "REGALOS DE SALIDA", home_gifts_url, class: "dropdown-item" %>
                <%= link_to "CAJITAS/BOLSITAS", home_boxes_url, class: "dropdown-item" %>
                <%= link_to "COMPLEMENTOS", home_accessories_url, class: "dropdown-item" %>
                <%= link_to "ARTICULOS DE MADERA", home_articles_url, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "IMPRIMIBLES", home_printable_url, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "CONTACTO", new_contact_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>