config/routes.rb
Rails.application.routes.draw do
  
  
  resources :gallery_images
  resources :orders
  root 'home#index'
  
  get 'home/Q_and_A', to: 'home#Q_and_A'
  get 'home/login', to: 'home#login'
  get 'home/childish', to: 'home#childish'
  get 'home/printable', to: 'home#printable'
  get 'home/accessories', to: 'home#accessories'
  get 'home/articles', to: 'home#articles'
  get 'home/adult', to: 'home#adult'
  get 'home/boxes', to: 'home#boxes'
  get 'home/gifts', to: 'home#gifts'
  get 'home/memories', to: 'home#memories'
  get 'home/others', to: 'home#others'
  get 'home/wedding', to: 'home#wedding'

  resources :galleries do
    resources :images, :only => [:create, :destroy] # support #create and #destroy
  end 
  resources :models
  resources :categories
  resources :events
  resources :social_networks
  resources :profiles
  resources :contacts
  resources :questions

  namespace :admin do
    get 'home/index'
  end

  devise_for :users, :controllers => { :passwords => 'scope/passwords', :registrations => 'scope/registrations'}
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord
  belongs_to :gallery

  mount_uploader :image, ImageUploader

  validates :image,
            format:{ with: %r{\.(gif|jpg|jpeg|png)\z}i, message: "Wrong file format" }
end

app/controllers/gallery_images_controller.rb
class GalleryImagesController < ApplicationController
  before_action :set_gallery_image, only: [:show, :destroy]

  layout 'admin'

  # GET /gallery_images
  # GET /gallery_images.json
  def index
    @gallery_images = GalleryImage.all
  end

  # GET /gallery_images/1
  # GET /gallery_images/1.json
  def show
  end

  # GET /gallery_images/new
  def new
    @gallery_image = GalleryImage.new
    @galleries = Gallery.find(params[:id_gallery])
    puts @galleries.id
  end

  # GET /gallery_images/1/edit
  def edit
  end

  # POST /gallery_images
  # POST /gallery_images.json
  def create
    @gallery_image = GalleryImage.new(gallery_image_params)

    @gallery_image.image = params[:file]

    if @gallery_image.save
      @galleries = Gallery.find_by(id: @gallery_image.gallery_id)
      redirect_to :controller => 'galleries', :action => 'show', :id => @galleries
      flash[:notice] = "Imagen agregada exitosamente."

    # respond_to do |format|
    #   if @gallery_image.save
    #     format.html { redirect_to @gallery_image, notice: 'Gallery image was successfully created.' }
    #     format.json { render :show, status: :created, location: @gallery_image }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
    #   end
    # end
    end
  end

  # PATCH/PUT /gallery_images/1
  # PATCH/PUT /gallery_images/1.json
  def update
    respond_to do |format|
      if @gallery_image.update(gallery_image_params)
        format.html { redirect_to @gallery_image, notice: 'Gallery image was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery_image }
      else
        format.html { render :edit }
        format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gallery_images/1
  # DELETE /gallery_images/1.json
  def destroy
    if @gallery_image.destroy
      @galleries = Gallery.find_by(id: @gallery_image.gallery_id)
      redirect_to :controller => 'galleries', :action => 'show', :id => @galleries
      flash[:notice] = "Imagen eliminada exitosamente."

    # respond_to do |format|
    #   format.html { render :template => "galleries/show", :locals => { :id => @galleries }, notice: 'Gallery image was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery_image
      @gallery_image = GalleryImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_image_params
      params.require(:gallery_image).permit(:image, :gallery_id)
    end
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/views/gallery_images/_form.html.erb
  <div class="content">
      <%= form_for gallery_image, html: { multipart: true } do |f| %>
          <% if gallery_image.errors.any? %>
            <div id="error_explanation">
              <div class="alert alert-danger">
                <span><b> Error - </b> </span>
                <ul>
                <% gallery_image.errors.messages.values.each do |message| %>
                  <% message.each do |m| %>
                    <li><%= m %></li>
                  <% end %>
                <% end %>
                </ul>
              </div> 
            </div>
          <% end %>

          <div class="row">
              <div class="col-md-6">
                  <div class="form-group">
                    <div class="field">
                      <label>Seleccionar Imágenes <strong class="form-label">*</strong></label>
                      <%= f.file_field :image %>
                    </div>
                  </div>
              </div>
          </div>

          <div class="hidden">
            <%= f.text_field :gallery_id, value: @galleries.id %>
          </div>

          <div class="actions text-center">
            <%= f.submit "Guardar", class: "btn btn-info btn-fill btn-wd" %>
          </div>

        <% end %>
  </div>

app/views/gallery_images/edit.html.erb
<h1>Editing Gallery Image</h1>

<%= render 'form', gallery_image: @gallery_image %>

<%= link_to 'Show', @gallery_image %> |
<%= link_to 'Back', gallery_images_path %>

app/views/gallery_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gallery Images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Gallery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gallery_images.each do |gallery_image| %>
      <tr>
        <td><%= gallery_image.image %></td>
        <td><%= gallery_image.gallery %></td>
        <td><%= link_to 'Show', gallery_image %></td>
        <td><%= link_to 'Edit', edit_gallery_image_path(gallery_image) %></td>
        <td><%= link_to 'Destroy', gallery_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery Image', new_gallery_image_path %>

app/views/gallery_images/new.html.erb
<div class="content">
	<div class="container-fluid">
	 	<div class="row">
	    	<div class="col-lg-8 col-md-7">
	      		<div class="card">
		              <div class="header">
		                  <h4 class="title">Nueva Imagen</h4>
		              </div>
						<%= render 'form', gallery_image: @gallery_image  %>
				</div>
	    	</div>
	 	 </div>
	</div>
</div>

app/views/gallery_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @gallery_image.image %>
</p>

<p>
  <strong>Gallery:</strong>
  <%= @gallery_image.gallery %>
</p>

<%= link_to 'Edit', edit_gallery_image_path(@gallery_image) %> |
<%= link_to 'Back', gallery_images_path %>